from __medico import Medico
from __enfermeiro import Enfermeiro
from __cirurgiao import Cirurgiao
from __recepcionista import Recepcionista
from __anestesista import Anestesista

medico = Medico('Jonathan', 1000, 8, '1', 'M')
enfermeiro = Enfermeiro('Thiago', 900, 6, '2', 'M')
cirurgiao = Cirurgiao('Hellen', 2000, 4, '3', 'F')
recepcionista = Recepcionista('Pedro', 1200, 6, '4', 'M')
anestesista = Anestesista('Mara', 1800, 8, '5', 'F')

print('########################################################################################################')
medico.nomeEmpregado()
medico.exibir_cargo()
medico.salarioMensal()
medico.horas_extras()
medico.selecionar_cargo_bonificacao()
medico.horas_mes()
medico.horas_almoço()
medico.sal_anual()
medico.quant_horas_anos()
print('########################################################################################################')
enfermeiro.nomeEmpregado()
enfermeiro.exibir_cargo()
enfermeiro.salarioMensal()
enfermeiro.horas_extras()
enfermeiro.selecionar_cargo_bonificacao()
enfermeiro.horas_mes()
enfermeiro.horas_almoço()
enfermeiro.sal_anual()
enfermeiro.quant_horas_anos()
print('########################################################################################################')
anestesista.nomeEmpregado()
anestesista.exibir_cargo()
anestesista.salarioMensal()
anestesista.horas_extras()
anestesista.selecionar_cargo_bonificacao()
anestesista.horas_mes()
anestesista.horas_almoço()
anestesista.sal_anual()
anestesista.quant_horas_anos()
print('########################################################################################################')
cirurgiao.nomeEmpregado()
cirurgiao.exibir_cargo()
cirurgiao.salarioMensal()
cirurgiao.horas_extras()
cirurgiao.selecionar_cargo_bonificacao()
cirurgiao.horas_mes()
cirurgiao.horas_almoço()
cirurgiao.sal_anual()
cirurgiao.quant_horas_anos()
print('########################################################################################################')
recepcionista.nomeEmpregado()
recepcionista.exibir_cargo()
recepcionista.salarioMensal()
recepcionista.horas_extras()
recepcionista.selecionar_cargo_bonificacao()
recepcionista.horas_mes()
recepcionista.horas_almoço()
recepcionista.sal_anual()
recepcionista.quant_horas_anos()
print('########################################################################################################')
